name: CI/CD

on:
  push:
    branches: [develop, main]

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    uses: shipyard-io/templates/.github/workflows/reusable-prepare.yml@main
    secrets:
      ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}

  build:
    needs: [prepare]
    uses: shipyard-io/templates/.github/workflows/reusable-build-docker.yml@main
    with:
      app-name: ${{ needs.prepare.outputs['app-name'] }}
    secrets: inherit

  setup-vps:
    uses: shipyard-io/templates/.github/workflows/reusable-provision-vps.yml@main
    secrets: inherit

  setup-traefik:
    needs: [setup-vps]
    uses: shipyard-io/templates/.github/workflows/reusable-upgrade-traefik.yml@main
    secrets: inherit

  deploy:
    needs: [prepare, build, setup-traefik]
    uses: shipyard-io/templates/.github/workflows/reusable-deploy-ssh.yml@main
    with:
      app-name: ${{ needs.prepare.outputs['app-name'] }}
      image-tag: ${{ needs.build.outputs['image-tag'] }}
      health-check-path: ${{ needs.prepare.outputs['health-check-path'] }}
    secrets: inherit

  notify:
    needs: [prepare, build, deploy]
    if: always()
    uses: shipyard-io/templates/.github/workflows/reusable-notify.yml@main
    with:
      app-name: ${{ needs.prepare.outputs['app-name'] }}
      app-domain: ${{ needs.prepare.outputs['app-domain'] }}
      status: ${{ needs.deploy.result }}
      commit-message: ${{ github.event.head_commit.message }}
      actor: ${{ github.actor }}
    secrets: inherit
